# Generated by Django 3.2.7 on 2024-06-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20240603_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='importancia',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=50),
        ),
    ]
