# Generated by Django 3.2.7 on 2024-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('general', 'General'), ('gerencia', 'Gerencia'), ('recursos_humanos', 'Recursos Humanos')], default='general', max_length=20),
        ),
    ]
