# Generated by Django 4.2.11 on 2026-02-05 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="fecha_baja",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="is_baja",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BajaEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_baja", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tipo_baja",
                    models.CharField(
                        choices=[
                            ("TEMPORAL", "Temporal"),
                            ("DEFINITIVA", "Definitiva"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bajas",
                        to="equipos.equipo",
                    ),
                ),
            ],
        ),
    ]
