# Generated by Django 4.2.11 on 2026-02-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0002_equipo_fecha_baja_equipo_is_baja_bajaequipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="antiguedad",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="codigo_postal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="domicilio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="nombre_responsable",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="rpe_responsable",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
