# Generated by Django 4.2.11 on 2026-02-05 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipos", "0003_equipo_antiguedad_equipo_codigo_postal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotivoBaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="bajaequipo",
            name="comentarios",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bajaequipo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="direccion_ip",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="direccion_mac",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="entidad",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="municipio",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="bajaequipo",
            name="motivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bajas",
                to="equipos.motivobaja",
            ),
        ),
    ]
