# Generated by Django 4.2.11 on 2026-02-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0006_equipo_infraestructura_critica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="numero_inventario",
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddConstraint(
            model_name="equipo",
            constraint=models.UniqueConstraint(
                condition=models.Q(numero_inventario__isnull=False)
                & ~models.Q(numero_inventario=""),
                fields=("numero_inventario",),
                name="unique_numero_inventario_nonempty",
            ),
        ),
    ]
